name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  ALLURE_TOKEN: 011fe067-9a03-49bf-b1ca-c7db4b20bbaf
  ALLURE_ENDPOINT: https://allure.autotests.cloud/
  ALLURE_PROJECT_ID: 4539
  ALLURE_RESULTS: allure-results

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t pw-tests-image .

      - name: Run Playwright tests inside Docker container
        run: docker run --rm -v "${{ github.workspace }}/allure-results:/app/allure-results" pw-tests-image

      - uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
      
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1 
      
      - name: Send report to Allure TestOps
        run: allurectl upload --endpoint $ALLURE_ENDPOINT --project-id $ALLURE_PROJECT_ID --token $ALLURE_TOKEN $ALLURE_RESULTS

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 1

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
